# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1f4h_KxTb9uf7z1Q4zF6fB8ZwLCkB23Ak
"""

import matplotlib.pyplot as plt

labels = [
    "Small\nSparse",
    "Small\nDense",
    "Medium\nSparse",
    "Medium\nDense",
    "Large\nSparse",
    "Large\nDense"
]

dijkstra = [0.00228, 0.00871, 0.09100, 0.39332, 0.60691, 3.16349]
floyd = [0.01090, 0.00792, 0.51654, 0.47154, 3.98705, 3.83911]

# -------------------------
# Graph 1
# -------------------------

plt.figure(figsize=(10,5))
plt.plot(labels, dijkstra, marker='o', linewidth=2, label='Repeated Dijkstra')
plt.plot(labels, floyd, marker='s', linewidth=2, label='Floyd-Warshall')

plt.title("Execution Time Comparison")
plt.xlabel("Graph Type")
plt.ylabel("Time (seconds)")
plt.grid(True)
plt.legend()

plt.tight_layout()
plt.show()


# -------------------------
# Graph 2
# -------------------------

vertices = [50,200,400]

dijkstra_sparse = [0.00228,0.09100,0.60691]
dijkstra_dense = [0.00871,0.39332,3.16349]

floyd_sparse = [0.01090,0.51654,3.98705]
floyd_dense = [0.00792,0.47154,3.83911]

plt.figure(figsize=(8,5))

plt.plot(vertices,dijkstra_sparse,'o-',label='Dijkstra Sparse')
plt.plot(vertices,dijkstra_dense,'o-',label='Dijkstra Dense')
plt.plot(vertices,floyd_sparse,'s--',label='Floyd Sparse')
plt.plot(vertices,floyd_dense,'s--',label='Floyd Dense')

plt.title("Effect of Graph Density")
plt.xlabel("Number of Vertices")
plt.ylabel("Time (seconds)")
plt.grid(True)
plt.legend()

plt.tight_layout()
plt.show()